import React from "react";
import {
  FileText,
  Activity,
  History,
  Download,
  Share2,
  Terminal,
  ExternalLink,
  ShieldCheck,
  Sparkles,
} from "lucide-react";
import { PaperAnalysis } from "../types/paper";

interface NavbarProps {
  currentAnalysis: PaperAnalysis | null;
  onOpenHistory: () => void;
  historyCount: number;
}

export const Navbar: React.FC<NavbarProps> = ({
  currentAnalysis,
  onOpenHistory,
  historyCount,
}) => {
  const [copied, setCopied] = React.useState(false);

  const handleShare = () => {
    if (!currentAnalysis) return;
    navigator.clipboard.writeText(
      `${currentAnalysis.paperDetails.title} - Analysis via ArXivArchitect: ${window.location.href}`
    );
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportMarkdown = () => {
    if (!currentAnalysis) return;
    const { paperDetails, coreConcept, flowchart, studentOpportunities } =
      currentAnalysis;

    const md = `# ${paperDetails.title}
**Authors:** ${paperDetails.authors} (${paperDetails.year})  
**Venue / arXiv:** ${paperDetails.venueOrArxiv}  
**URL:** ${paperDetails.url}

---

## 1. CORE CONCEPT EXTRACTION
*Word Count: ${coreConcept.wordCount} words*

### Problem Statement
${coreConcept.problemStatement}

### Primary Methodology
${coreConcept.primaryMethodology}

### Key Mathematical & Algorithmic Breakthroughs
${coreConcept.keyBreakthroughs.map((b) => `- ${b}`).join("\n")}

### Plain-Language Synthesis
${coreConcept.accessibleSynthesis}

---

## 2. ARCHITECTURAL FLOWCHART
[FLOWCHART]
\`\`\`mermaid
${flowchart.mermaidCode}
\`\`\`

---

## 3. FUTURE WORK & INTERNSHIP OPPORTUNITIES
${studentOpportunities
  .map(
    (opp, i) => `### Idea ${i + 1}: ${opp.title} (${opp.difficulty})
- **Exact Extension:** ${opp.exactExtension}
- **Targeted Metric:** ${opp.targetedMetric}
- **Recommended Tech Stack:** ${opp.recommendedTechStack.join(", ")}
- **Why Great for Resume:** ${opp.whyGreatForResume}

#### 4-Week Milestone Roadmap:
${opp.fourWeekRoadmap
  .map((w) => `  - **${w.week} (${w.milestone}):** ${w.tasks}`)
  .join("\n")}

#### STAR Resume Bullet:
> ${opp.resumeBulletSTAR}
`
  )
  .join("\n\n")}

---
*Generated by ArXivArchitect - CS Research & System Architecture Agent*
`;

    const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute(
      "download",
      `${paperDetails.title.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 30)}_Architect_Report.md`
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const tokenUsage = currentAnalysis?.usage?.totalTokenCount || 3500;
  const budgetRatio = Math.round((tokenUsage / 25000) * 100);

  return (
    <header className="sticky top-0 z-40 w-full border-b border-slate-800/80 bg-slate-950/80 backdrop-blur-md">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
        {/* Brand */}
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 via-blue-600 to-cyan-500 p-0.5 shadow-lg shadow-blue-500/20">
            <div className="w-full h-full bg-slate-950 rounded-[10px] flex items-center justify-center">
              <Terminal className="w-5 h-5 text-cyan-400" />
            </div>
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-bold text-lg tracking-tight bg-gradient-to-r from-white via-slate-100 to-slate-400 bg-clip-text text-transparent">
                ArXivArchitect
              </span>
              <span className="text-[10px] font-mono uppercase tracking-wider px-2 py-0.5 rounded-full bg-cyan-950/70 text-cyan-300 border border-cyan-800/60 font-medium">
                Research Agent
              </span>
            </div>
            <p className="text-xs text-slate-400 hidden sm:block">
              Paper Deconstruction • Mermaid Flowcharts • Student Resume Lab
            </p>
          </div>
        </div>

        {/* Center / Token Efficiency Indicator */}
        <div className="hidden md:flex items-center gap-2 bg-slate-900/90 border border-slate-800 px-3 py-1.5 rounded-full text-xs">
          <ShieldCheck className="w-4 h-4 text-emerald-400" />
          <span className="text-slate-300 font-medium">Token Guardrail:</span>
          <span className="text-emerald-400 font-mono font-semibold">
            {tokenUsage.toLocaleString()} / 25,000 max
          </span>
          <div className="w-12 h-1.5 bg-slate-800 rounded-full overflow-hidden ml-1">
            <div
              className="h-full bg-emerald-500 rounded-full"
              style={{ width: `${Math.min(budgetRatio, 100)}%` }}
            />
          </div>
          <span className="text-[11px] text-slate-500 font-mono">
            ({budgetRatio}%)
          </span>
        </div>

        {/* Actions */}
        <div className="flex items-center gap-2">
          {currentAnalysis && (
            <>
              <button
                onClick={handleShare}
                className="p-2 text-slate-300 hover:text-white hover:bg-slate-800 rounded-lg transition-colors border border-transparent hover:border-slate-700 text-xs flex items-center gap-1.5"
                title="Share link"
              >
                <Share2 className="w-4 h-4" />
                <span className="hidden sm:inline">
                  {copied ? "Copied!" : "Share"}
                </span>
              </button>

              <button
                onClick={handleExportMarkdown}
                className="px-3 py-1.5 text-xs font-medium text-slate-200 bg-slate-800/80 hover:bg-slate-700/80 border border-slate-700 rounded-lg transition-colors flex items-center gap-1.5"
                title="Export analysis as Markdown"
              >
                <Download className="w-3.5 h-3.5 text-blue-400" />
                <span className="hidden sm:inline">Export Report</span>
              </button>
            </>
          )}

          <button
            onClick={onOpenHistory}
            className="relative px-3 py-1.5 text-xs font-medium text-slate-300 hover:text-white bg-slate-900 hover:bg-slate-800 border border-slate-800 rounded-lg transition-colors flex items-center gap-1.5"
          >
            <History className="w-3.5 h-3.5 text-amber-400" />
            <span>History</span>
            {historyCount > 0 && (
              <span className="w-4 h-4 rounded-full bg-amber-500/20 text-amber-300 border border-amber-500/30 text-[10px] font-mono flex items-center justify-center">
                {historyCount}
              </span>
            )}
          </button>
        </div>
      </div>
    </header>
  );
};
